version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_CREATE_TOPICS: 'raw-analytics-events:1:1'
    networks:
      - app-network

  kafkaui:
    restart: on-failure
    image: 'docker.redpanda.com/vectorized/console:master-173596f'
    ports:
      - '8686:8080'
    environment:
      - KAFKA_BROKERS=localhost:9092
    networks:
      - app-network
    extra_hosts:
      - 'localhost:host-gateway'
    depends_on:
      kafka:
        condition: service_started

networks:
  app-network:
    driver: bridge